# Generated by Django 4.2.9 on 2024-12-04 16:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo_evento', models.IntegerField(choices=[(1, 'Interno'), (2, 'Público')], default=2, verbose_name='Tipo de evento')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora do evento')),
                ('data', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Agenda de eventos',
                'verbose_name_plural': 'Agendas de eventos',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('conteudo', tinymce.models.HTMLField(verbose_name='Conteúdo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='blog', verbose_name='Banner')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
            ],
            options={
                'verbose_name': 'Categoria do blog',
                'verbose_name_plural': 'Categorias do blog',
            },
        ),
        migrations.CreateModel(
            name='ClasseSimbolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
            ],
            options={
                'verbose_name': 'Classe de símbolo',
                'verbose_name_plural': 'Classes de símbolos',
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoMediacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', tinymce.models.HTMLField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Mediação',
                'verbose_name_plural': 'Mediação',
            },
        ),
        migrations.CreateModel(
            name='Simbolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='simbolo', verbose_name='Imagem')),
                ('palavras_chave', models.CharField(max_length=255, verbose_name='Palavras-chave')),
                ('classes', models.ManyToManyField(blank=True, related_name='%(class)s_classes', to='publicacoes.classesimbolo', verbose_name='Classes')),
            ],
            options={
                'verbose_name': 'Símbolo',
                'verbose_name_plural': 'Símbolos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
