# Generated by Django 4.2.9 on 2024-12-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Agendado'), (2, 'Realizado'), (3, 'Cancelado'), (4, 'Solicitado')], null=True, verbose_name='Status')),
                ('precisa_retorno', models.BooleanField(default=False, verbose_name='Precisa de retorno')),
                ('data', models.DateField(verbose_name='Data')),
                ('recomendacoes', models.TextField(blank=True, null=True, verbose_name='Recomendações')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='AtendimentoBanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('instrucoes', models.TextField(blank=True, null=True, verbose_name='Instruções')),
            ],
            options={
                'verbose_name': 'Atendimento Banho',
                'verbose_name_plural': 'Atendimentos Banhos',
            },
        ),
        migrations.CreateModel(
            name='AtendimentoTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('modificado_em', models.DateTimeField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('instrucoes', models.TextField(blank=True, null=True, verbose_name='Instruções')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atendimento', to='atendimento.atendimento')),
            ],
            options={
                'verbose_name': 'Atendimento Terapia',
                'verbose_name_plural': 'Atendimentos Terapias',
            },
        ),
    ]
