# Generated by Django 4.2.9 on 2024-12-04 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
        ('atendimento', '0001_initial'),
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentoterapia',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimentoterapia',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimentoterapia',
            name='terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_terapia', to='contrib.terapia', verbose_name='Terapia'),
        ),
        migrations.AddField(
            model_name='atendimentobanho',
            name='atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_atendimento', to='atendimento.atendimento'),
        ),
        migrations.AddField(
            model_name='atendimentobanho',
            name='banho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_banho', to='contrib.banho'),
        ),
        migrations.AddField(
            model_name='atendimentobanho',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimentobanho',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='consulente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_consulente', to='usuarios.consulente', verbose_name='Consulente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='criado_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_criado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_guia', to='contrib.entidade', verbose_name='Guia'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='mediador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_mediador', to='usuarios.trabalhador', verbose_name='Mediador'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_medium', to='usuarios.trabalhador', verbose_name='Médium'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
