
USER_PAPEL_ADMIN = 1
USER_PAPEL_COMUM = 2

CHOICES_USER_PAPEL = (
    (USER_PAPEL_ADMIN, 'Administrador'),
    (USER_PAPEL_COMUM, 'Comum'),
)

MASCULINO = 1
FEMININO = 2

CHOICES_SEXO = (
    (MASCULINO, 'Masculino'),
    (FEMININO, 'Feminino')
)

METODO_REGISTRO_EMAIL = 1
METODO_REGISTRO_GOOGLE = 2

CHOICES_METODO_REGISTRO = [
    (METODO_REGISTRO_EMAIL, 'Email'),
    (METODO_REGISTRO_GOOGLE, 'Google'),
]